import { streamText, generateText, convertToModelMessages } from "ai";
import { createOpenAI } from "@ai-sdk/openai";
import { createAnthropic } from "@ai-sdk/anthropic";
import { createGoogleGenerativeAI } from "@ai-sdk/google";

export const runtime = "edge";
export const maxDuration = 120; // Increased for dual-agent processing

/** Max conversation turns sent to the model (keeps prefill fast) */
const MAX_CONTEXT_MESSAGES = 30;

// ─── Agent 1: Generator ─────────────────────────────────────────────────────
// Focuses on understanding requirements and producing complete diagram code.
const GENERATOR_PROMPT = `You are an expert diagram code generator (Agent 1 in a dual-agent system).
Analyze the user's request and generate diagram code.

Generate BOTH:
1. A Mermaid diagram in a \`\`\`mermaid code block
2. A draw.io XML diagram in a \`\`\`drawio-xml code block

Rules:
- Mermaid: pick the best diagram type (flowchart, sequence, class, state, ER, gantt…). Use clear, descriptive node labels. Ensure valid syntax.
- Draw.io: output valid mxGraphModel XML wrapped in <mxfile><diagram name="Page-1"><mxGraphModel><root>…</root></mxGraphModel></diagram></mxfile>. Use mxCell elements with proper geometry, styling, and spacing.
- Both diagrams must represent the same concept accurately.
- Focus on completeness and structural correctness.
- If the user uploads an image, recreate it in both formats.
- If the user's message is NOT about diagrams, respond normally without code blocks.`;

// ─── Agent 2: Optimizer / Validator ─────────────────────────────────────────
// Receives Agent 1's output via shared context and validates / optimises it.
const OPTIMIZER_PROMPT = `You are an expert diagram code reviewer and syntax validator (Agent 2 in a dual-agent system).
The previous assistant message contains diagram code generated by Agent 1.
Your job is to review, fix, and optimise it.

Tasks:
1. VALIDATE Mermaid syntax – check for invalid node IDs, missing brackets / semicolons, incorrect arrow syntax (-->, --->, -.->, ==>, etc.), unbalanced quotes, subgraph issues, and special characters that need quoting.
2. VALIDATE draw.io XML – check for well-formed XML, proper mxCell hierarchy (parent references), required attributes (id, parent, vertex/edge), valid geometry values, and correct mxfile/diagram/mxGraphModel nesting.
3. OPTIMISE – improve layout spacing, colours, visual clarity, and readability.
4. FIX – correct every error found.

Output format:
- A Mermaid diagram in a \`\`\`mermaid code block
- A draw.io XML diagram in a \`\`\`drawio-xml code block
- After the code blocks, briefly explain what was reviewed and any fixes / improvements made.

Critical rules:
- ALWAYS output BOTH code blocks, even if no changes were needed.
- Mermaid syntax must be renderable by Mermaid.js v11+.
- Draw.io XML must be valid and parseable by the draw.io engine.
- Node IDs in Mermaid must not contain unquoted special characters.
- Preserve the original diagram's intent and structure from the user's request.`;

/** Message sent to Agent 2 to trigger the review (shared-memory handoff). */
const HANDOFF_MESSAGE =
  "Please review the diagram code in your previous response. " +
  "Fix any syntax errors, optimise the layout and styling, and output the final corrected versions of both the Mermaid and draw.io diagrams.";

// ─── Provider helpers ───────────────────────────────────────────────────────

function getModel(provider: string, modelId: string, baseUrl: string, apiKey: string) {
  switch (provider) {
    case "openai": {
      const openai = createOpenAI({
        baseURL: baseUrl || undefined,
        apiKey: apiKey || process.env.OPENAI_API_KEY || "",
      });
      return openai(modelId);
    }
    case "anthropic": {
      const anthropic = createAnthropic({
        baseURL: baseUrl || undefined,
        apiKey: apiKey || process.env.ANTHROPIC_API_KEY || "",
      });
      return anthropic(modelId);
    }
    case "google": {
      const google = createGoogleGenerativeAI({
        baseURL: baseUrl || undefined,
        apiKey: apiKey || process.env.GOOGLE_GENERATIVE_AI_API_KEY || "",
      });
      return google(modelId);
    }
    case "custom":
    default: {
      const custom = createOpenAI({
        baseURL: baseUrl || undefined,
        apiKey: apiKey || "",
      });
      return custom(modelId);
    }
  }
}

// ─── Route handler ──────────────────────────────────────────────────────────

export async function POST(req: Request) {
  try {
    const {
      messages,
      provider = "openai",
      model: modelId = "gpt-4o",
      baseUrl = "",
      apiKey = "",
    } = await req.json();

    const model = getModel(provider, modelId, baseUrl, apiKey);

    const trimmedMessages =
      messages.length > MAX_CONTEXT_MESSAGES
        ? messages.slice(-MAX_CONTEXT_MESSAGES)
        : messages;
    const modelMessages = await convertToModelMessages(trimmedMessages);

    // ── Phase 1: Generator Agent (non-streaming) ────────────────────────────
    // Agent 1 analyses the request and produces raw diagram code.
    // Its full output is kept in memory (shared context for Agent 2).
    const agent1Result = await generateText({
      model,
      system: GENERATOR_PROMPT,
      messages: modelMessages,
    });

    const agent1Text = agent1Result.text;
    const hasDiagramCode = /```(mermaid|drawio-xml)/.test(agent1Text);

    // If Agent 1 didn't produce any diagrams (e.g. a greeting), return its
    // response directly — no need for the optimiser pass.
    if (!hasDiagramCode) {
      const encoder = new TextEncoder();
      const passthrough = new ReadableStream({
        start(controller) {
          controller.enqueue(encoder.encode(agent1Text));
          controller.close();
        },
      });
      return new Response(passthrough, {
        headers: { "Content-Type": "text/plain; charset=utf-8" },
      });
    }

    // ── Phase 2: Optimizer Agent (streaming) ─────────────────────────────────
    // Agent 2 receives the full conversation PLUS Agent 1's output (shared
    // memory) so it can review, fix syntax errors, and optimise the code.
    const agent2Messages = [
      ...modelMessages,
      { role: "assistant" as const, content: agent1Text },
      { role: "user" as const, content: HANDOFF_MESSAGE },
    ];

    const result = streamText({
      model,
      system: OPTIMIZER_PROMPT,
      messages: agent2Messages,
    });

    return result.toTextStreamResponse();
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "Internal server error";
    console.error("[chat] Error:", message);
    return new Response(message, { status: 500 });
  }
}
